"use client";

import { useState, useMemo, useEffect } from "react";
import {
  Product,
  ProductVariant,
  Attribute,
  ProductSpec,
  Category,
} from "../../../generated/prisma/client";
import {
  ShoppingCart,
  Minus,
  Plus,
  Check,
  Zap,
  Truck,
  ShieldCheck,
  RefreshCcw,
} from "lucide-react";
import { useCartStore } from "@/store/cart-store";
import { toast } from "react-hot-toast";
import WishlistButton from "@/components/product/wishlist-button";
import { useRouter } from "next/navigation";

interface ProductInfoProps {
  product: Product & {
    variants: ProductVariant[];
    specs: (ProductSpec & { attribute: Attribute })[];
    category: Category;
    brand?: { name: string } | null;
  };
}

export default function ProductInfo({ product }: ProductInfoProps) {
  const router = useRouter();

  // 1. Safely parse the "options" JSON generated by the admin form
  const parsedOptions = useMemo(() => {
    try {
      return product.options ? JSON.parse(product.options) : [];
    } catch (e) {
      return [];
    }
  }, [product.options]);

  // 2. Initialize Selection State with the first available value of each option
  const [selectedOptions, setSelectedOptions] = useState<
    Record<string, string>
  >(() => {
    const init: Record<string, string> = {};
    parsedOptions.forEach((opt: any) => {
      if (opt.values && opt.values.length > 0) {
        init[opt.name] = opt.values[0];
      }
    });
    return init;
  });

  // 3. Fallback for simple/legacy variants
  const [selectedVariant, setSelectedVariant] = useState<ProductVariant | null>(
    product.variants.length > 0 ? product.variants[0] : null,
  );

  // 4. Smart Variant Matcher & Image Syncer
  useEffect(() => {
    if (product.variants.length === 0) return;

    if (parsedOptions.length > 0) {
      // Find the specific variant that contains ALL the selected option strings
      const matchedVariant = product.variants.find((v) => {
        return parsedOptions.every((opt: any) => {
          const selectedValue = selectedOptions[opt.name];
          if (!selectedValue) return false;
          return v.name.toLowerCase().includes(selectedValue.toLowerCase());
        });
      });

      if (matchedVariant) {
        setSelectedVariant(matchedVariant);
        // ✅ Sync Image to Gallery Gallery using a Custom Window Event
        if ((matchedVariant as any).image) {
          window.dispatchEvent(
            new CustomEvent("variantImageChange", {
              detail: { image: (matchedVariant as any).image },
            }),
          );
        }
      }
    }
  }, [selectedOptions, product.variants, parsedOptions]);

  const [quantity, setQuantity] = useState(1);
  const [isAdded, setIsAdded] = useState(false);

  const addToCart = useCartStore((state) => state.addItem);
  const setCheckoutIds = useCartStore((state) => state.setCheckoutIds);

  const basePrice = Number(product.price);
  const variantPrice = selectedVariant
    ? Number(selectedVariant.price)
    : basePrice;
  const discountPrice = product.discountPrice
    ? Number(product.discountPrice)
    : null;

  const finalPrice = discountPrice || variantPrice;
  const isOnSale = discountPrice && discountPrice < variantPrice;
  const discountPercent = isOnSale
    ? Math.round(((variantPrice - discountPrice) / variantPrice) * 100)
    : 0;

  const formatPrice = (p: number) => {
    return new Intl.NumberFormat("en-NP", {
      style: "currency",
      currency: "NPR",
      maximumFractionDigits: 0,
    }).format(p);
  };

  const prepareCartItem = () => {
    let image = "/placeholder.jpg";
    if (selectedVariant && (selectedVariant as any).image) {
      image = (selectedVariant as any).image;
    } else {
      try {
        const images = product.images ? JSON.parse(product.images) : [];
        if (images.length > 0) image = images[0];
      } catch (e) {}
    }

    return {
      productId: product.id,
      variantId: selectedVariant?.id || null,
      name:
        product.name + (selectedVariant ? ` (${selectedVariant.name})` : ""),
      price: finalPrice,
      image,
      quantity,
      stock: selectedVariant ? selectedVariant.stock : product.stock,
      categoryName: product.category.name,
    };
  };

  const handleAddToCart = () => {
    const item = prepareCartItem();
    addToCart(item);

    setIsAdded(true);
    setTimeout(() => setIsAdded(false), 2000);

    toast.custom(
      (t) => (
        <div
          className={`bg-base-100 border border-base-200 shadow-xl rounded-2xl p-3 flex items-center gap-3 min-w-[250px] transform transition-all duration-300 ${t.visible ? "opacity-100 translate-y-0" : "opacity-0 translate-y-2"}`}
        >
          <div className="w-10 h-10 bg-base-200 rounded-lg overflow-hidden shrink-0 border border-base-300">
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img
              src={item.image}
              alt={product.name}
              className="w-full h-full object-cover"
            />
          </div>
          <div className="flex-1 min-w-0">
            <h4 className="font-bold text-xs truncate pr-2">{product.name}</h4>
            <div className="flex items-center gap-1 mt-0.5">
              <span className="badge badge-xs badge-success text-white gap-1 px-1 py-1">
                <Check size={8} /> Added to Cart
              </span>
            </div>
          </div>
        </div>
      ),
      { position: "bottom-right", duration: 3000 },
    );
  };

  const handleBuyNow = () => {
    const item = prepareCartItem();
    addToCart(item);
    const itemKey = `${item.productId}-${item.variantId ?? "base"}`;
    setCheckoutIds([itemKey]);
    router.push("/checkout");
  };

  const isOutOfStock = selectedVariant
    ? selectedVariant.stock === 0
    : product.stock === 0;

  return (
    <div className="flex flex-col h-full">
      {/* 1. Brand & Title */}
      <div className="mb-4">
        <div className="flex items-center justify-between mb-1">
          {product.brand && (
            <span className="text-xs font-bold text-primary tracking-wider uppercase">
              {product.brand.name}
            </span>
          )}
          <div className="flex gap-2">
            {isOnSale && (
              <span className="badge badge-error badge-sm text-white font-bold border-none shadow-sm">
                Save {discountPercent}%
              </span>
            )}
            {isOutOfStock ? (
              <span className="badge badge-neutral badge-sm text-white font-bold border-none shadow-sm">
                Sold Out
              </span>
            ) : (
              <span className="badge badge-success/10 badge-sm text-success font-bold border-none">
                In Stock
              </span>
            )}
          </div>
        </div>
        <h1 className="text-2xl lg:text-3xl font-black text-base-content leading-tight mb-2 tracking-tight">
          {product.name}
        </h1>

        {/* 2. Pricing */}
        <div className="flex items-end gap-3 bg-base-200/50 w-fit px-4 py-2 rounded-xl border border-base-200">
          <div className="text-2xl font-black text-primary">
            {formatPrice(finalPrice)}
          </div>
          {isOnSale && (
            <div className="text-sm text-base-content/40 line-through font-medium mb-0.5">
              {formatPrice(variantPrice)}
            </div>
          )}
        </div>
        {selectedVariant && selectedVariant.sku && (
          <p className="text-[10px] font-mono opacity-50 mt-1 uppercase tracking-widest">
            SKU: {selectedVariant.sku}
          </p>
        )}
      </div>

      {/* 3. ✅ COMPACT VARIANTS SELECTION */}
      {parsedOptions.length > 0 ? (
        <div className="mb-5 space-y-4">
          {parsedOptions.map((opt: any) => {
            const isColor = opt.name.toLowerCase().includes("color");

            return (
              <div key={opt.name}>
                <div className="flex items-center justify-between mb-2">
                  <span className="font-bold text-xs uppercase tracking-wide opacity-70 flex items-center gap-1">
                    {opt.name}:{" "}
                    <span className="text-base-content opacity-100 font-black">
                      {selectedOptions[opt.name]}
                    </span>
                  </span>
                </div>

                <div className="flex flex-wrap gap-2">
                  {opt.values.map((val: string) => {
                    const isSelected = selectedOptions[opt.name] === val;

                    // 🎨 Swatch Mode for "Color"
                    if (isColor) {
                      let hex = "#e5e7eb";
                      const matchingVariant = product.variants.find(
                        (v) =>
                          v.name.toLowerCase().includes(val.toLowerCase()) &&
                          v.colorCode,
                      );
                      if (matchingVariant?.colorCode)
                        hex = matchingVariant.colorCode;

                      return (
                        <button
                          key={val}
                          onClick={() =>
                            setSelectedOptions((prev) => ({
                              ...prev,
                              [opt.name]: val,
                            }))
                          }
                          className={`relative w-10 h-10 rounded-full flex items-center justify-center transition-all ${
                            isSelected
                              ? "ring-2 ring-primary ring-offset-1 scale-110 shadow-sm"
                              : "hover:scale-110 border border-base-300 shadow-sm"
                          }`}
                          title={val}
                        >
                          <span
                            className="w-8 h-8 rounded-full block border border-black/10"
                            style={{ backgroundColor: hex }}
                          />
                          {isSelected && (
                            <Check
                              size={14}
                              className="absolute text-white mix-blend-difference drop-shadow-md"
                            />
                          )}
                        </button>
                      );
                    }

                    // 📦 Standard Button Mode
                    return (
                      <button
                        key={val}
                        onClick={() =>
                          setSelectedOptions((prev) => ({
                            ...prev,
                            [opt.name]: val,
                          }))
                        }
                        className={`px-4 py-1.5 rounded-lg border-2 font-bold text-xs transition-all ${
                          isSelected
                            ? "border-primary bg-primary/5 text-primary shadow-sm"
                            : "border-base-200 bg-base-100 hover:border-primary/40 text-base-content/70 hover:text-base-content"
                        }`}
                      >
                        {val}
                      </button>
                    );
                  })}
                </div>
              </div>
            );
          })}
        </div>
      ) : product.variants.length > 0 ? (
        // Fallback for simple legacy variants
        <div className="mb-5 space-y-3">
          <div className="flex items-center justify-between">
            <span className="font-bold text-xs uppercase tracking-wide opacity-70">
              Select Option:{" "}
              <span className="text-base-content opacity-100 ml-1">
                {selectedVariant?.name}
              </span>
            </span>
          </div>
          <div className="grid grid-cols-2 sm:grid-cols-3 gap-2">
            {product.variants.map((variant) => {
              const isSelected = selectedVariant?.id === variant.id;
              const hasColor =
                variant.colorCode && variant.colorCode !== "#ffffff";

              return (
                <button
                  key={variant.id}
                  onClick={() => setSelectedVariant(variant)}
                  className={`relative flex flex-col items-center justify-center p-2 rounded-xl border-2 transition-all ${
                    isSelected
                      ? "border-primary bg-primary/5 shadow-sm"
                      : "border-base-200 hover:border-primary/30 hover:bg-base-200/50"
                  }`}
                >
                  {hasColor && (
                    <span
                      className="w-3 h-3 rounded-full mb-1 shadow-sm border border-base-300"
                      style={{ backgroundColor: variant.colorCode || "#ccc" }}
                    />
                  )}
                  <span className="text-xs font-bold text-center leading-tight">
                    {variant.name}
                  </span>
                  {isSelected && (
                    <div className="absolute -top-1.5 -right-1.5 bg-primary text-white rounded-full p-0.5 shadow-sm">
                      <Check size={10} strokeWidth={3} />
                    </div>
                  )}
                </button>
              );
            })}
          </div>
        </div>
      ) : null}

      {/* 4. Actions & Layout spacing improved */}
      <div className="fixed bottom-0 left-0 right-0 p-4 bg-base-100 border-t border-base-200 z-40 lg:relative lg:p-0 lg:bg-transparent lg:border-none md:mt-auto">
        <div className="flex flex-col gap-4 max-w-md mx-auto lg:max-w-none">
          <div className="flex items-center gap-4">
            {/* Quantity */}
            <div className="flex items-center bg-base-200 rounded-xl h-12 px-2 border border-base-200 shadow-inner w-32 justify-between">
              <button
                onClick={() => setQuantity(Math.max(1, quantity - 1))}
                className="btn btn-ghost btn-xs btn-square hover:bg-base-300 rounded-lg"
                disabled={isOutOfStock}
              >
                <Minus size={16} />
              </button>
              <span className="font-bold text-base">{quantity}</span>
              <button
                onClick={() => setQuantity(quantity + 1)}
                className="btn btn-ghost btn-xs btn-square hover:bg-base-300 rounded-lg"
                disabled={
                  isOutOfStock ||
                  (selectedVariant
                    ? quantity >= selectedVariant.stock
                    : quantity >= product.stock)
                }
              >
                <Plus size={16} />
              </button>
            </div>

            {/* Wishlist */}
            <WishlistButton
              productId={product.id}
              className="btn btn-outline btn-circle h-12 w-12 min-h-0 border-base-300 flex items-center justify-center hover:bg-base-200 hover:border-base-300"
            />
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <button
              onClick={handleAddToCart}
              disabled={isAdded || isOutOfStock}
              className={`btn h-12 rounded-xl text-sm shadow-sm transition-all min-h-0 ${
                isAdded
                  ? "btn-success text-white"
                  : "btn-outline border-base-300 hover:bg-base-200 hover:border-base-300 text-base-content"
              }`}
            >
              {isAdded ? (
                <Check size={18} />
              ) : (
                <ShoppingCart size={18} className="mr-1 opacity-70" />
              )}
              {isAdded ? "Added to Cart" : "Add to Cart"}
            </button>

            <button
              onClick={handleBuyNow}
              disabled={isOutOfStock}
              className="btn btn-primary h-12 min-h-0 rounded-xl text-sm shadow-md shadow-primary/20 hover:scale-[1.02] transition-transform"
            >
              <Zap size={18} className="mr-1 fill-current text-warning" />
              Buy it Now
            </button>
          </div>
        </div>
      </div>

      {/* 5. Modern Trust Badges */}
      <div className="grid grid-cols-3 gap-3 mt-8 pt-6 border-t border-base-200">
        <div className="flex flex-col items-center text-center group cursor-default">
          <div className="w-10 h-10 rounded-full bg-blue-500/10 text-blue-600 flex items-center justify-center mb-2 group-hover:scale-110 group-hover:bg-blue-500/20 transition-all">
            <Truck size={18} />
          </div>
          <h4 className="font-bold text-[11px] leading-tight text-base-content">
            Fast Delivery
          </h4>
          <span className="text-[9px] font-medium text-base-content/60 mt-0.5">
            Nationwide
          </span>
        </div>

        <div className="flex flex-col items-center text-center group cursor-default">
          <div className="w-10 h-10 rounded-full bg-emerald-500/10 text-emerald-600 flex items-center justify-center mb-2 group-hover:scale-110 group-hover:bg-emerald-500/20 transition-all">
            <ShieldCheck size={18} />
          </div>
          <h4 className="font-bold text-[11px] leading-tight text-base-content">
            Secure Pay
          </h4>
          <span className="text-[9px] font-medium text-base-content/60 mt-0.5">
            100% Safe
          </span>
        </div>

        <div className="flex flex-col items-center text-center group cursor-default">
          <div className="w-10 h-10 rounded-full bg-purple-500/10 text-purple-600 flex items-center justify-center mb-2 group-hover:scale-110 group-hover:bg-purple-500/20 transition-all">
            <RefreshCcw size={18} />
          </div>
          <h4 className="font-bold text-[11px] leading-tight text-base-content">
            Easy Returns
          </h4>
          <span className="text-[9px] font-medium text-base-content/60 mt-0.5">
            7 Days Policy
          </span>
        </div>
      </div>
    </div>
  );
}
